"""Generates docs/index.html from collections.json.

Add a new collection by appending an entry to collections.json, then run
this script. No manual HTML editing required.

Status is "open" (gets a storefront illustration in the scrolling street,
a link to its redirect, and a card in the "A Taste of Every Shop" grid) or
"coming-soon" (not shown anywhere yet -- there's no storefront illustration
to put in the street for a shop that hasn't launched). Adding an 8th, 9th,
... open collection needs no code changes here, but does need two new
image assets first (see "Assets" below).

Assets (not generated by this script):
  docs/assets/storefronts/<slug>.png -- the illustrated storefront shown
    in the scrolling street. Transparent background, consistent eye-level
    perspective across shops (see ../ShanezShertz's brief for the art).
  docs/assets/products/<slug>.jpg -- one representative product shot used
    in the "A Taste of Every Shop" grid. Its caption comes from this
    collection's "featured_title" in collections.json.
Both required for a collection to appear once its status is "open".
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent
COLLECTIONS = json.loads((ROOT / "collections.json").read_text(encoding="utf-8"))
DOCS = ROOT / "docs"

PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shanez Shertz</title>
<meta name="description" content="A universe of businesses that take ridiculous ideas completely seriously.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
</head>
<body>

<nav class="site-header">
  <a class="brand" href="/">
    <img src="assets/logo.png" alt="Shanez Shertz" class="logo">
    <span>Shanez Shertz</span>
  </a>
  <div class="navlinks">
    <a href="#mall">Shops</a>
    <span class="dot">&middot;&middot;&middot;&middot;&middot;</span>
    <a href="#about">About</a>
  </div>
</nav>

<div class="hero">
  <div class="street-scroll" id="street-scroll">
    <div class="street-track">
      <div class="buildings">
{buildings}
      </div>
      <div class="curb"></div>
      <div class="sidewalk"></div>
    </div>
  </div>
  <div class="edge-fade left"></div>
  <div class="edge-fade right"></div>
  <div class="arrow-hint left"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#211F1B" stroke-width="2.4"><polyline points="15 18 9 12 15 6"/></svg></div>
  <div class="arrow-hint right"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#211F1B" stroke-width="2.4"><polyline points="9 18 15 12 9 6"/></svg></div>
</div>

<div class="dots">
{dots}
</div>

<div class="marquee">
  <div class="marquee-track">OPEN 24/7 &middot; NO PARKING NEEDED &middot; {shop_count} SHOPS AND COUNTING &middot; OPEN 24/7 &middot; NO PARKING NEEDED &middot; {shop_count} SHOPS AND COUNTING &middot;</div>
</div>

<section class="featured" id="mall">
  <div class="featured-head">
    <span class="eyebrow">One from every shop</span>
    <h2>A Taste of Every Shop</h2>
  </div>
  <div class="featured-grid">
{featured_cards}
  </div>
</section>

<section class="blurb" id="about">
  <p>Shanez Shertz isn't one t-shirt brand. It's a mall full of them &mdash; a rejection-letter department, a wellness company that's questionable at best, a gallery that won't explain itself, and more opening soon. Nobody working here finds any of it remarkable.</p>
</section>

<footer class="site-footer">
  <div class="brand"><img src="assets/logo.png" alt="" class="logo-small"><span>&copy; 2026 Shanez Shertz</span></div>
  <div class="social-links">
    <a href="https://www.facebook.com/shanezshertz" aria-label="Facebook">Facebook</a>
    <a href="https://www.instagram.com/shanezshertz/" aria-label="Instagram">Instagram</a>
    <a href="https://www.tiktok.com/@shanezshertz" aria-label="TikTok">TikTok</a>
  </div>
</footer>

<script>
  var street = document.getElementById("street-scroll");
  street.addEventListener("wheel", function (e) {{
    if (Math.abs(e.deltaY) <= Math.abs(e.deltaX)) return;
    var atStart = street.scrollLeft <= 0;
    var atEnd = street.scrollLeft >= street.scrollWidth - street.clientWidth - 1;
    if ((e.deltaY < 0 && atStart) || (e.deltaY > 0 && atEnd)) return;
    street.scrollBy({{ left: e.deltaY, behavior: "instant" }});
    e.preventDefault();
  }}, {{ passive: false }});
</script>

</body>
</html>
"""

BUILDING_TEMPLATE = """        <div class="bldg" id="shop-{slug}">
          <img src="assets/storefronts/{slug}.png" alt="{name} storefront">
          <a class="enter-pill" href="{redirect}">ENTER &rarr;</a>
        </div>"""

DOT_TEMPLATE = '  <a href="#shop-{slug}" aria-label="{name}"></a>'

FEATURED_CARD_TEMPLATE = """    <div class="featured-card">
      <img src="assets/products/{slug}.jpg" alt="{featured_title}">
      <span class="tag">{name}</span>
      <div class="title">{featured_title}</div>
      <a href="{redirect}">Shop &rarr;</a>
    </div>"""


def build():
    open_collections = [c for c in COLLECTIONS if c["status"] == "open"]
    if not open_collections:
        raise ValueError("at least one collection must have status \"open\"")

    skipped = [c["name"] for c in COLLECTIONS if c["status"] not in ("open", "coming-soon")]
    if skipped:
        raise ValueError(f"unknown status for: {', '.join(skipped)}")

    buildings = "\n".join(BUILDING_TEMPLATE.format(**c) for c in open_collections)
    dots = "\n".join(DOT_TEMPLATE.format(**c) for c in open_collections)
    featured_cards = "\n".join(FEATURED_CARD_TEMPLATE.format(**c) for c in open_collections)

    html = PAGE_TEMPLATE.format(
        buildings=buildings,
        dots=dots,
        shop_count=len(open_collections),
        featured_cards=featured_cards,
    )
    (DOCS / "index.html").write_text(html, encoding="utf-8")

    coming_soon = len(COLLECTIONS) - len(open_collections)
    print(f"Built docs/index.html: {len(open_collections)} open" + (f", {coming_soon} coming-soon (not shown yet)" if coming_soon else ""))


if __name__ == "__main__":
    build()
